# Golang CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/filecoin-project/go-bs-lmdb
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...